apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone  
  region: us-west-2  
  version: "1.21"

managedNodeGroups:
  - name: capstone-nodes 
    instanceType: m5.large
    desiredCapacity: 3   
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true  
        albIngress: true  
        autoScaler: true  

