apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/capstone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 81
